### ISSUE TITLE
Warning in logcat on launch

### ISSUE THREAD

**Issue by mimi89999** [shymmq/librus-client-kotlin#13]
```
08-30 21:19:06.784 23050 23050 W System  : ClassLoader referenced unknown path: /data/app/com.wabadaba.dziennik-1/lib/arm
08-30 21:19:06.831 23050 23050 W System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
08-30 21:19:06.832 23050 23050 W System.err: 	at java.io.FileOutputStream.open(Native Method)
08-30 21:19:06.832 23050 23050 W System.err: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
08-30 21:19:06.832 23050 23050 W System.err: 	at org.jacoco.agent.rt.internal_773e439.output.FileOutput.openFile(FileOutput.java:67)
08-30 21:19:06.832 23050 23050 W System.err: 	at org.jacoco.agent.rt.internal_773e439.output.FileOutput.startup(FileOutput.java:49)
08-30 21:19:06.832 23050 23050 W System.err: 	at org.jacoco.agent.rt.internal_773e439.Agent.startup(Agent.java:122)
08-30 21:19:06.832 23050 23050 W System.err: 	at org.jacoco.agent.rt.internal_773e439.Agent.getInstance(Agent.java:50)
08-30 21:19:06.832 23050 23050 W System.err: 	at org.jacoco.agent.rt.internal_773e439.Offline.<clinit>(Offline.java:31)
08-30 21:19:06.832 23050 23050 W System.err: 	at org.jacoco.agent.rt.internal_773e439.Offline.getProbes(Offline.java:51)
08-30 21:19:06.832 23050 23050 W System.err: 	at com.wabadaba.dziennik.MainApplication.$jacocoInit(MainApplication.kt)
08-30 21:19:06.832 23050 23050 W System.err: 	at com.wabadaba.dziennik.MainApplication.<init>(MainApplication.kt)
08-30 21:19:06.832 23050 23050 W System.err: 	at java.lang.Class.newInstance(Native Method)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.Instrumentation.newApplication(Instrumentation.java:993)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5422)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-30 21:19:06.833 23050 23050 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-30 21:19:06.833 23050 23050 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 21:19:06.833 23050 23050 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-30 21:19:06.833 23050 23050 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by Frioo** [comment]
Does this still occur?
